# Lines configured by zsh-newuser-install

# history settings
export HISTFILE=~/.histfile
export HISTSIZE=2000
export SAVEHIST=2000
setopt hist_ignore_all_dups
bindkey -e

# Advanced tab-Completion
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

# Correction
# setup correctall

# Prompt
export PS1="%d %% "

# Miscellaneous
setopt autocd
setopt extendedglob

# java set home
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH="/usr/local/sbin:$PATH"

# Setting PATH for hadoop
export HADOOP_HOME=~/softwares/hadoop/
export PATH=$HADOOP_HOME/bin:$PATH

############ spark config #################
# Setting PATH for spark
export SPARK_HOME=~/softwares/spark
export PYSPARK_PYTHON=python3
export PATH=$SPARK_HOME/bin:$PATH

# Setting PATH for pyspark driver
#export PYSPARK_DRIVER_PYTHON=jupyter
#export PYSPARK_DRIVER_PYTHON_OPTS='notebook'
#export PYSPARK_SUBMIT_ARGS="--packages com.databricks:spark-xml_2.11:0.4.1 pyspark-shell"

# setting language
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# python path
export PYTHONPATH="${PYTHONPATH}"
export PATH=$PATH:/usr/local/mysql/bin

############ gremlin config #################
export PATH=${PATH}:~/softwares/gremlin/bin

# miniconda setup
export WORKON_HOME=~/miniconda3/envs/

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/vmarni/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/vmarni/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/vmarni/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/vmarni/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/ubuntu/.sdkman"
[[ -s "/home/ubuntu/.sdkman/bin/sdkman-init.sh" ]] && source "/home/ubuntu/.sdkman/bin/sdkman-init.sh"
